require 'faker'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Plant.destroy_all
Collection.destroy_all

10.times do
    User.create(
      username: Faker::TvShows::Friends.character.split(/ /).join(),
      password: "hi",
    )
  end

Plant.create(name: "Amaryllis", category: "Flowering", description: "Bulb flowering type plants that produce a cluster of attractive trumpet like flowers in different color variations.", light: "Bright Indirect", watering: "Water once a week or until top two inches of soil are dry.", soil: "Equal parts perlite and peat.", image: "https://www.edenbrothers.com/store/media/Bulbs-Flowers/resized/Amaryllis-Cherry-Nymph-1_medium.jpg")
Plant.create(name: "African Violet", category: "Flowering", description: "Saintpaulia is a genus comprising of approximately 20 species and subspecies, and many varietes.Various species includes different sizes, flower colors and foliage types.", light: "Bright Indirect", watering: "Water once a week or when soil is slightly dry to the touch.", soil: "Well-drained, slightly acidic soil.", image: "https://www.gardeningknowhow.com/wp-content/uploads/2019/03/african-violet-blooms.jpg")
Plant.create(name: "Barberton Daisy", category: "Flowering", description: "A flowering pot plant displaying striking flowers.", light: "Bright Direct", watering: "Water once a day.", soil: "A peat based potting mix with 2 parts peat and 1 part perlite.", image:"https://plantingman.com/wp-content/uploads/2017/03/Barberton-daisy-plant.jpg")
Plant.create(name: "Calla Lily", category: "Flowering", description: "Keeping this rhizome happy indoors is a matter of paying attention to some very basic growing conditions.", light: "Bright Direct", watering: "Water daily or at least keep the soil moist.", soil: "Standard potting soil.", image:"https://images-na.ssl-images-amazon.com/images/I/61%2BCtc46ycL._AC_SX466_.jpg")
Plant.create(name: "Flamingo Flower", category: "Flowering", description: "The beautiful waxed effect flaming flower plant makes a great ornamental plant that stands out looking lush.", light: "Bright Indirect", watering: "Water daily or at least keep the soil moist.", soil: "Equal parts perlite and peat.", image:"https://cdn.shopify.com/s/files/1/0888/2934/products/263_1024x1024@2x.jpg?v=1555511570")
Plant.create(name: "Flaming Sword", category: "Flowering", description: "This species features a red sword like flower head which can grow up to 2ft tall and attractive mottled leaves.", light: "Bright Indirect", watering: "Water once a week or until top two inches of soil are dry", soil: "A peat based potting mix.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7HUWoeqyWxPq-mpZtwK06miiSMuRlKHwDdg&usqp=CAU")
Plant.create(name: "Moth Orchid", category: "Flowering", description: "The moth orchid like other plants from the orchid displays many bright colorful flowers.", light: "Bright Direct", watering: "Water a few times a week, allow soil to be dry to the touch.", soil: "Orchid Potting Mix", image:"https://images-na.ssl-images-amazon.com/images/I/71BVSiqfyJL._AC_SL1500_.jpg")
Plant.create(name: "Ornamental Pepper Plant", category: "Flowering", description: "A flowering pot type species grown for it's attractive fruit.", light: "Bright Direct", watering: "Water once a day. Do not let soil get dry.", soil: "Standard potting soil.", image:"https://mobileimages.lowes.com/product/converted/022532/022532146742.jpg?size=pdhi")
Plant.create(name: "Peace Lily", category: "Flowering", description: "The simplistic look of the glossy leaves and the fantastic white lily that sits above the foliage provides a minimalistic room with an added touch of simplicity.", light: "Bright Indirect", watering: "Water daily or at least keep the soil moist.", soil: "Equal parts perlite and peat.", image:"https://asset.bloomnation.com/c_pad,d_vendor:global:catalog:product:image.png,f_auto,fl_preserve_transparency,q_auto/v1605324215/vendor/192/catalog/product/2/0/20160405042709_file_5703e75d99844.jpg")
Plant.create(name: "Poison Primrose", category: "Flowering", description: "Small clusters of flowers in different color variations.", light: "Bright Indirect", watering: "Water daily or at least keep the soil moist.", soil: "Peat Potting Mix", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAsbhj983xUaKmfNga2XW2EaQZEV-veXeZYQ&usqp=CAU")
Plant.create(name: "Scarlet Star", category: "Flowering", description: "A popular bromeliad species grown for it's green leathery foliage and bright red or orange bract.", light: "Bright Indirect", watering: "Roots should be misted daily, water a few times a week allowing soil to completely dry.", soil: "One part potting soil to one part pumice or bark", image:"https://www.guide-to-houseplants.com/images/bromeliad-scarlet-star.jpg")
Plant.create(name: "Urn Plant", category: "Flowering", description: "The Urn plant is also known as the silver vase plant (scientific name: Aechmea Fasciata).", light: "Bright Indirect", watering: "Water a few times a week, allow soil to be dry to the touch.", soil: "One part potting soil to one part pumice or bark", image:"https://www.houseplantsexpert.com/image-files/Aechmea-Fasciata.jpg")

Plant.create(name: "Aluminum Plant", category: "Foliage", description: "An easy going house plant that is generally simple to please.", light: "Bright Indirect", watering: "Water a few times a week, keep the soil moist.", soil: "One part relite with two parts peat.", image:"https://images-na.ssl-images-amazon.com/images/I/71s6UjTHjLL._AC_SX569_.jpg")
Plant.create(name: "Areca Palm", category: "Foliage", description: "A cane type palm growing up to 8ft tall with mulitple stems.", light: "Bright Indirect", watering: "Water a few times a week, allow top soil to dry.", soil: "A mixture of 1 part peat, 1 part pine bark and 1 part coarse sand.", image:"https://target.scene7.com/is/image/Target/GUEST_e1ec1247-90cd-4881-8ccc-c620c77dc358?wid=488&hei=488&fmt=pjpeg")
Plant.create(name: "Arrowhead", category: "Foliage", description: "Very similar species as the Philodendron and from the same family.", light: "Bright Indirect", watering: "Water a few times a week, allow top soil to dry.", soil: "Peat based soil.", image:"https://i5.walmartimages.com/asr/b5617fe7-8d1c-43e5-8693-ee4081abef15_1.f2acfdb3d2493727b672904e31e9887c.jpeg?odnWidth=612&odnHeight=612&odnBg=ffffff")
Plant.create(name: "Cast Iron Plant", category: "Foliage", description: "Receives its common name for its ability to withstand neglect. A nice an easy to care for foliage plant.", light: "Bright Indirect", watering: "Water a few times a week, allow top soil to dry.", soil: "Any well-draining soil.", image:"https://images-na.ssl-images-amazon.com/images/I/516wzBuj4RL._AC_SY450_.jpg")
Plant.create(name: "Chinese Evergreen", category: "Foliage", description: "Grown primarily for the attractive leathery leaves.", light: "Bright Indirect", watering: "Water daily, keeping soil moist.", soil: "Equal parts perlite and peat.", image:"https://i.pinimg.com/originals/ed/3a/db/ed3adb47671c70337994bb8b0483ef93.jpg")
Plant.create(name: "Croton", category: "Foliage", description: "Not an easy species to grow, although it's foliage is outstanding in color.", light: "Bright Direct", watering: "Water a few times a week.", soil: "A peat (2 parts) based potting mixture with perlite or sand (1 part)", image:"https://images-na.ssl-images-amazon.com/images/I/71u6EGwLp6L._AC_SL1500_.jpg")
Plant.create(name: "Elephant's Ear", category: "Foliage", description: "A foliage plant with very distinct looking leaves - but it does flower.", light: "Bright Indirect", watering: "Water a little, but often - keeping soil moist at all times.", soil: "Fast draining peat based potting mix.", image:"https://cdn11.bigcommerce.com/s-421f8/images/stencil/original/products/548/3640/Landscape_Plants_New_18__19576.1593639999.png?c=2")
Plant.create(name: "Golden Pothos", category: "Foliage", description: "A climbing species that grows well indoors with the correct care given.", light: "Bright Indirect", watering: "Water once a week.", soil: "Well draining potting soil.", image:"https://www.plantshed.com//media/catalog/product/cache/1/image/1200x1200/9df78eab33525d08d6e5fb8d27136e95/p/s/ps18003_hanging_golden_pothos.jpg")
Plant.create(name: "Heart of Jesus", category: "Foliage", description: "The caladium is a tuber species which displays the attractive bicolor leaves.", light: "Bright Indirect", watering: "Water a few times a week, keeping the soil moist.", soil: "Well draining potting soil.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw7V_MKtn8p0EXvfTBe92cdUbMHRPIzw1fEQ&usqp=CAU")
Plant.create(name: "Madagascar Dragon Tree", category: "Foliage", description: "Most definitely one of the easiest indoor plants to grow and maintain. Dracaena Marginata trees can grow up to 6ft high.", light: "Bright Indirect", watering: "Water a few times a week, keeping the soil slightly moist.", soil: "All purpose potting mix.", image:"https://images-na.ssl-images-amazon.com/images/I/81PVOax5KAL._AC_SX425_.jpg")
Plant.create(name: "Lucky Bamboo", category: "Foliage", description: "An easy to grow plant which can thrive in soil or water.", light: "Bright Indirect", watering: "If in a vase, water once a week, if it is soil, water when soil is slightly dry to touch.", soil: "Well draining potting soil.", image:"https://assets.eflorist.com/site/63088400/assets/products/PHR_/sku6470432.jpg")
Plant.create(name: "Rubber Plant", category: "Foliage", description: "One of the ficus greats with large glossy oval shaped leaves.", light: "Bright Indirect", watering: "Water a few times a week, allowing top soil to dry.", soil: "One part peat, one part pine park, and one part perlite.", image:"https://cdn.shopify.com/s/files/1/0260/3037/4957/products/medium-plant-ficus-black-pot_800x.jpg?v=1611373347")
Plant.create(name: "Spider Plant", category: "Foliage", description: "This plant can survive with minimal care/attention and can manage low temperatures.", light: "Bright Indirect", watering: "Water a few times a week. They like plenty of water.", soil: "All purpose potting mix.", image:"https://images-na.ssl-images-amazon.com/images/I/71sOoiJzLWL._SL1000_.jpg")
Plant.create(name: "ZZ Plant", category: "Foliage", description: "The worst thing you can do to a ZZ plant is over water it, otherwise it survives well.", light: "Bright Indirect", watering: "Water once a week.", soil: "Well draining potting mix with perlite mixed in.", image:"https://images-na.ssl-images-amazon.com/images/I/81F0BQ6NExL._AC_SY679_.jpg")

# Plant.create(name: "Aloe Vera", category: "Succulent/Cacti", description: "The Aloe Vera is a common house plant that has many potential heath benefits. An indoor Aloe is easy to grow and not demanding.", light: "Bright Indirect", watering: "Water once a week or until soil is dry.", soil: "Cactus potting mixture", image:"https://assets.eflorist.com/site/EF-2287/assets/products/PHR_/sku6701208.jpg")
# Plant.create(name: "Bunny Ear Cactus", category: "Succulent/Cacti", description: "The bunny ear cactus, also known as the polka dot cactus is a very popular plant.", light: "", watering: "", soil: "", image:"")
# Plant.create(name: "Christmas Cactus", category: "Succulent/Cacti", description: "The Christmas cactus is the ideal house plant if a grower likes to see flowers blooming from November - January.", light: "", watering: "", soil: "", image:"")
# Plant.create(name: "Coral Cactus", category: "Succulent/Cacti", description: "The Coral cactus is much as the name states in one sense and not in another. It's similar looking to coral but not an actual cactus.", light: "", watering: "", soil: "", image:"")
# Plant.create(name: "Donkey's Tail", category: "Succulent/Cacti", description: "The Donkeys tail is a trailing succulent species suitable for growing in a hanging basket.", light: "", watering: "", soil: "", image:"")
# Plant.create(name: "Golden Barrel Cactus", category: "Succulent/Cacti", description: "Globe shaped type cacti suitable for growing in conservatories, on patios or other indoor glass type rooms.", light: "", watering: "", soil: "", image:"")
# Plant.create(name: "Jade Plant", category: "Succulent/Cacti", description: "The Jade plant also known as the money plant is a very popular houseplant. Scientific names Crassula argentea. C.ovata, and C.portulacea.", light: "", watering: "", soil: "", image:"")
# Plant.create(name: "Snake Plant", category: "Succulent/Cacti", description: "The mother in laws tongue (also known as snake plant) is a flowering species that is primarily grown for it's slick looking long leaves.", light: "", watering: "", soil: "", image:"")
# Plant.create(name: "Peruvian Apple Cactus", category: "Succulent/Cacti", description: "The apple cactus (also known as columnar, column, hedge cactus and others) displays a prominent ribbed column stem with brown colored spines.", light: "", watering: "", soil: "", image:"")
# Plant.create(name: "Tiger Jaws", category: "Succulent/Cacti", description: "This species flowers at the end of summer and display jaw like leaves that are toothed.", light: "", watering: "", soil: "", image:"")
# Plant.create(name: "Watermelon Peperomia", category: "Succulent/Cacti", description: "A low growing bushy type plant with striking leaves.", light: "", watering: "", soil: "", image:"")
# Plant.create(name: "Zebra Haworthia", category: "Succulent/Cacti", description: "Similar in appearance and has the same care needs as the Aloe plant. Thick and warty leaves.", light: "", watering: "", soil: "", image:"")

15.times do
    Collection.create(
        user: User.all.sample,
        plant: Plant.all.sample,
        nickname: ""
    )
end